name: Automated Android Package (APK) Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest source
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build a (debug) APK using the latest source
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dot-debug
          path: app/build/outputs/apk/debug/app-debug.apk